---
title: "BFA - Variables harmonization for all surveys and years"
author: "Groupe 1"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```


```{r packages needed}
library(haven)
library(labelled)
library(tidyverse)
library(dplyr)
library(Hmisc)
library(gtsummary)
library(readxl)
library(foreign)
```



```{r}
rm(list = ls())
```

```{r environment settings}

path =here::here()
dir_input_data = paste0(path,"/input_data")
dir_output_data = paste0(path,"/output_data")
```

```{r read harmonization excel file}

BFA_Harmonization_variables <- read_excel(paste0(dir_input_data,"/BFA_Harmonization.xlsx"), 
    sheet = "variables_harmonization")
#View(BFA_Harmonization_variables)

BFA_Harmonization_description <- read_excel(paste0(dir_input_data,"/BFA_Harmonization.xlsx"), 
    sheet = "description")
#View(BFA_Harmonization_description)
```

```{r data importation}

lst_data = BFA_Harmonization_description$Data
lst_test = BFA_Harmonization_description$Name

for(i in 1:length(lst_data)) {                              # Head of for-loop
  assign(lst_test[i],                                   # Read and store data frames
         read_sav(paste0(dir_input_data,"/",lst_data[i])))
}

```

for(i in 1:length(lst_data)) {                              # Head of for-loop


```{r select and rename columns needed}

for (j in 1:length(lst_test)){
         df=  get(lst_test[j], envir = .GlobalEnv)
          for (i in 1:nrow(BFA_Harmonization_variables)){
            df[,BFA_Harmonization_variables$NewVariable_Name[i]]=ifelse(is.na(BFA_Harmonization_variables[i,lst_test[j]]),NA,df[,BFA_Harmonization_variables[i,lst_test[j]][[1]]])
          }
     df<-df %>%select(BFA_Harmonization_variables$NewVariable_Name)
    write_dta(df, paste0(dir_output_data,"/",lst_test[j],".dta"))
}

```

